variables:
  buildConfiguration: 'Release'

steps:
- task: XamariniOS@2
  inputs:
    solutionFile: 'MobileApp.iOS.csproj'
    configuration: '$(Debug)'
    packageApp: false
    buildForSimulator: true
